##
## @doc 
##   project builder
AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub CodeBuild

Parameters:
  GithubRepo:
    Description: Github repository, absolute url (e.g. https://github.com/:user/:repo)
    Type: String

  CodeBuildImage:
    Description: Builder toolchain
    Type: String
    Default: aws/codebuild/docker:1.12.1

  CodeBuildTimeout:
    Description: Duration of build process in minutes
    Type: Number
    Default: 10

  CodeBuildWeeklyBuildsRule:
    Description: Whether to enable periodic builds for this project
    Type: String
    Default: DISABLED

Resources:

  ReCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}
      Description: !Sub ${AWS::StackName}
      ServiceRole: ci-cd
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
        Image:
          Ref: CodeBuildImage
      Source:
        Location: !Sub ${GithubRepo}
        Type: GITHUB
      TimeoutInMinutes: !Sub ${CodeBuildTimeout}

  CloudWatchRule:
    Type: AWS::Events::Rule
    Properties:
      Description: !Sub CloudWatch event scheduler for ${AWS::StackName}
      Name: !Sub ${AWS::StackName}-scheduler
      ScheduleExpression: rate(7 days)
      State: !Sub ${CodeBuildWeeklyBuildsRule}
      Targets:
      - Id: !Sub ${AWS::StackName}-schedule
        Arn: !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${AWS::StackName}
        RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ci-cd-role-lambda
